# Generated by Django 2.1 on 2018-11-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(default='Description', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.FloatField(default=0.0, max_length=10),
            preserve_default=False,
        ),
    ]
